# -*- coding: utf-8 -*-
"""05/06/2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMWa7Ile74nJVbeKy5P2xJlQnhm8BwPt
"""

age=18
print(id(age))

salary=age
print(id(salary))

salary=20
print(id(salary))

x="RAJASTHAN"
print(x[5])

x="RAJASTHAN"
print(x[0:4])

x="RAJASTHAN"
print(x[4:])

x="RAJASTHAN"
print(x[:6])

x="RAJASTHAN"
print(x[0:4:1])

x="RAJASTHAN"
print(x[0:4:2])

x="RAJASTHAN"
print(x[2: : 2])

x="RAJASTHAN"
print(x[ :4:2])

x="RAJASTHAN"
print(x[-1:-3:-1])

x="RAJASTHAN"
print(x[-4:-1:1])

#conditional statement
print("hello")

age=int(input())
if(age>=18):
   print("he can vote ")
else:
  print("he can not vote")

age=21
country="jaipur"
if(age>=18and country=="india"):
   print("he can vote ")
else:
  print("he can not vote")

country="india"
if(country=="india"):
     print("aadhar card")
else:
      print("no aadhar")

country="india"
age=17
if(age>=18):
   print("voter id+ aadhar card")
elif(country=="india"):
     print("aadhar card")
else:
      print("no aadhar")

a=11
if(a%2==0):
   print("even number")
else:
  print("odd number")

a= int(input())
if(a==1):
   print("january")
elif(a==2):
    print("feb")
elif(a==3):
     print("march")
elif(a==4):
     print("april")
elif(a==5):
     print("may")
elif(a==6):
     print("june")
elif(a==7):
     print("july")
elif(a==8):
     print("aug")
elif(a==9):
     print("sep")
elif(a==10):
     print("oct")
elif(a==11):
     print("nov")
elif(a==12):
     print("dec")
else:
     print("wrong")

a= int(input())
if(a==1):
   print("sunday")
elif(a==2):
    print("monday")
elif(a==3):
     print("tuesday")
elif(a==4):
     print("wednesday")
elif(a==5):
     print("thrusday")
elif(a==6):
     print("friday")
elif(a==7):
     print("saturday")
else:
     print("wrong")

a= int and float (input())
if(a>=91):
   print("excellent")
elif(a>=81):
     print("very good")
elif(a>=70):
    print("good")
else:
     print("fail")

