# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gry1shx8gHldsGEghkAzfw5lQvjfbKMc
"""

x=10
print(id(x))

y=x
print(id(y))

x=10
print(x, id(x))



y=x
print("y:",y, id(y))

y=15
print(id(x), id(y))

10/3

10// 3

1+3*5/5-8*6

x=5
x //=5
print(x)

x=10
x==10
y=10
y>18 and x==10

14&13

14|13

20&25

11>>1

23//4

14<<2

"J" in "JAIPUR"

"b" in "krishna"

"PURR" not in "JAIPUR"

x=10
type(x) is int

type(x) is not str

y=50
type(x) is str