# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0MeSu1QEQUze0wAz0W37CJcRvfO61yx
"""

#function
#named block
#function a block of code that we can run anytime
#code readability
#code reusability
#debugging is easy

def greeting():
   print("hello")

greeting()

def greeting():
  name="tushar"
  print("hello",name)

greeting()

def greeting(username):
  print("hello",username)

#argument
greeting("krishna")

greeting("ravi sir")
greeting("krishna")
greeting("guddu")

def sumNo(x,y):
  print(x+y)

sumNo(10,20)

def sumNo():
  c=x+y
  print(c)
#function outside
x=20
y=30
sumNo()

def func():
     print("inside function", x+10)
x=10
func()
print(x)

del y

def func():
  global x
  x=x+10
  print("inside function", x)
x=10
func()
print(x)

def additionNo(num):
   print("num:",id(num))
   print(num+10)

x=10
print("before function",id(x))
additionNo(x)

def evenOdd(x):
    if (x%2==0):
        print(True)
    else:
        print(False)

x=int(input("enter a number:"))
evenOdd(x)

def divisible(x, y):
    if (x% 6 == 0 and y% 6 == 0):
        print("Hey")
    else:
        print("Hello")
x=int(input("enter a number:"))
y=int(input("enter a number:"))
divisible(x, y)

